baseURL: https://efmi-standard.org/
title: eFMI®
theme: ma-hugo-theme
params:
  logo: /images/ma-logos/dark/eFMI-bare.svg
  github: modelica/efmi-standard.org
  email: efmi-info@googlegroups.com
  darkMode: true
menu:
  main:
    - pageRef: introduction
      identifier: introduction
      name: Introduction
      url: /introduction/
      weight: 1
    
    - pageRef: resources
      identifier: resources
      name: Resources
      url: /resources/
      weight: 2
    
    - pageRef: publications
      identifier: publications
      name: Publications
      url: /publications/
      weight: 3
    
    - pageRef: standard
      identifier: standard
      name: Standard
      url: /standard/
      weight: 4
    
    - pageRef: tools
      identifier: tools
      name: Tools
      url: /tools/
      weight: 5
    
    - pageRef: news
      identifier: news
      name: News
      url: /news/
      weight: 6
    
    - pageRef: about
      identifier: about
      name: About
      url: /about/
      weight: 7